module.exports = {
    touchDevices: '--touch-devices',
    touchEvents: '--touch-events',

    userAgent: '--user-agent',
    useMobileUserAgent: '--use-mobile-user-agent',
    reduceUserAgentMinorVersion: '--reduce-user-agent-minor-version',
    reduceUserAgentPlatformOscpu: '--reduce-user-agent-platform-oscpu',

    disableFineGrainedTimeZoneDetection: '--disable-fine-grained-time-zone-detection',
    disablePerUserTimezone: '--disable-per-user-timezone',
    timeZoneForTesting: '--time-zone-for-testing',

    acceptLang: '--accept-lang',
    reduceAcceptLanguage: '--reduce-accept-language',
    defaultCountryCode: '--default-country-code',

    disableRemoteFonts: '--disable-remote-fonts',
    disableFontSubpixelPositioning: '--disable-font-subpixel-positioning',
    disableLcdText: '--disable-lcd-text',
    disablePreferCompositingToLcdText: '--disable-prefer-compositing-to-lcd-text',
    disableScrollToTextFragment: '--disable-scroll-to-text-fragment',
    enableFontAntialiasing: '--enable-font-antialiasing',

    disableJavascriptHarmonyShipping: '--disable-javascript-harmony-shipping',
    javascriptHarmony: '--javascript-harmony',
    jsFlags: '--js-flags',

    disableExtensions: '--disable-extensions',
    disableExtensionsExcept: '--disable-extensions-except',
    disableExtensionsFileAccessCheck: '--disable-extensions-file-access-check',
    disableExtensionsHttpThrottling: '--disable-extensions-http-throttling',
    disableFeatures: '--disable-features',
    disableDefaultApps: '--disable-default-apps',
    disableComponentExtensionsWidthBackgroundPages: '--disable-component-extensions-with-background-pages',
    enableExperimentalExtensionApis: '--enable-experimental-extension-apis',
    listApps: '--list-apps',
    listAudioDevices: '--list-audio-devices',
    loadApps: '--load-apps',
    loadExtension: '--load-extension',

    disableFileSystem: '--disable-file-system',
    disableMediaSessionApi: '--disable-media-session-api',
    disableNotifications: '--disable-notifications',
    disablePermissionsApi: '--disable-permissions-api',
    disablePresentationApi: '--disable-presentation-api',
    disableRemotePlaybackApi: '--disable-remote-playback-api',
    disableScreenOrientationLock: '--disable-screen-orientation-lock',
    disableSharedWorkers: '--disable-shared-workers',
    disableSpeechApi: '--disable-speech-api',
    disableSpeechSynthesisApi: '--disable-speech-synthesis-api',
    disabled3DApis: '--disable-3d-apis',
    disableTouchDragDrop: '--disable-touch-drag-drop',
    disableSystemFontCheck: '--disable-system-font-check',

    enableExperimentalWebPlatformFeatures: '--enable-experimental-web-platform-features',
    enableExperimentalWebassemblyFeatures: '--enable-experimental-webassembly-features',
    enableExperimentalWebassemblyStackSwitching: '--enable-experimental-webassembly-stack-switching',
    enablePrivacySandboxAdsApis: '--enable-privacy-sandbox-ads-apis',
    enableUsermediaScreenCapturing: '--enable-usermedia-screen-capturing',
    disableBlinkFeatures: '--disable-blink-features',

    qsAddFakeBluetoothDevices: '--qs-add-fake-bluetooth-devices',
    qsAddFakeCastDevices: '--qs-add-fake-cast-devices',

    sslVersionMax: '--ssl-version-max',
    sslVersionMin: '--ssl-version-min',

    processPerSite: '--process-per-site',
    sitePerProcess: '--site-per-process',
    singleProcess: '--single-process',
    processPerTab: '--process-per-tab',
    isolateOrigins: '--isolate-origins',
    isolatedAppOrigins: '--isolated-app-origins',
    isolatedContextOrigin: '--isolated-context-origins',
    isolationByDefault: '--isolation-by-default',
    disableSiteIsolationForPolicy: '--disable-site-isolation-for-policy',
    disableSiteIsolationTrials: '--disable-site-isolation-trials',
    disableAutoWptOriginIsolation: '--disable-auto-wpt-origin-isolation',

    useFakeCodecForPeerConnection: '--use-fake-codec-for-peer-connection',
    useFakeDeviceForMediaStream: '--use-fake-device-for-media-stream',
    useFakeMjpegDecodeAccelerator: '--use-fake-mjpeg-decode-accelerator',
    useFakeUiForFedcm: '--use-fake-ui-for-fedcm',
    useFakeUiForMediaStream: '---use-fake-ui-for-media-stream',
    useFileForFakeAudioCapture: '--use-file-for-fake-audio-capture',

    simulateCriticalUpdate: '--simulate-critical-update',
    simulateElevatedRecovery: '--simulate-elevated-recovery',
    simulateOutdated: '--simulate-outdated',
    simulateOutdatedNoAu: '--simulate-outdated-no-au',
    simulateUpdateErrorCode: '--simulate-update-error-code',
    simulateUpdateHresult: '--simulate-update-hresult',
    simulateUpgrade: '--simulate-upgrade',

    remoteAllowOrigins: '--remote-allow-origins',
    disableWebSecurity: '--disable-web-security',
    disabledCookieEncryption: '--disable-cookie-encryption',
    enableExperimentalCookieFeatures: '--enable-experimental-cookie-features',
    disableDatabases: '--disable-databases',
    disableLocalStorage: '--disable-local-storage',
    unlimitedStorage: '--unlimited-storage',
    disableDomainReliability: '--disable-domain-reliability',
    enablePotentiallyAnnoyingSecurityFeatures: '--enable-potentially-annoying-security-features',
    disableDomainBlockingFor3dApis: '--disable-domain-blocking-for-3d-apis',
    disablePopupBlocking: '--disable-popup-blocking',
    disableGaiaServices: '--disable-gaia-services',
    disableV8IdleTasks: '--disable-v8-idle-tasks',
    disableHidBlocklist: '--disable-hid-blocklist',
    disableHidDetectionOnOobe: '--disable-hid-detection-on-oobe',
    disableUsbKeyboardDetect: '--disable-usb-keyboard-detect',
    disableSigninScopedDeviceId: '--disable-signin-scoped-device-id',
    disableArcCpuRestriction: '--disable-arc-cpu-restriction',
    reportVp9AsAnUnsupportedMimeType: '--report-vp9-as-an-unsupported-mime-type',
    safebrowsingEnableEnhancedProtection: '--safebrowsing-enable-enhanced-protection',
    safebrowsingManualDownloadBlacklist: '--safebrowsing-manual-download-blacklist',
    disableAppContentVerification: '--disable-app-content-verification',
    disableCheckerImaging: '--disable-checker-imaging',

    disablePepper3d: '--disable-pepper-3d',
    disablePepper3dImageChromium: '--disable-pepper-3d-image-chromium',
    disableUseMojoVideoDecoderForPepper: '--disable-use-mojo-video-decoder-for-pepper',

    disableAcceleratedMjpegDecode: '--disable-accelerated-mjpeg-decode',
    disableAcceleratedVideoDecode: '--disable-accelerated-video-decode',
    disableAcceleratedVideoEncode: '--disable-accelerated-video-encode',

    disableGpu: '--disable-gpu',
    disableGpuCompositing: '--disable-gpu-compositing',
    disableGpuDriverBugWorkarounds: '--disable-gpu-driver-bug-workarounds',
    disableGpuEarlyInit: '--disable-gpu-early-init',
    disableGpuMemoryBufferCompositorResources: '--disable-gpu-memory-buffer-compositor-resources',
    disableGpuMemoryBufferVideoFrames: '--disable-gpu-memory-buffer-video-frames',
    disableGpuProcessCrashLimit: '--disable-gpu-process-crash-limit',
    disableGpuProcessForDx12InfoCollection: '--disable-gpu-process-for-dx12-info-collection',
    disableGpuProgramCache: '--disable-gpu-program-cache',
    disableGpuRasterization: '--disable-gpu-rasterization',
    disableGpuSandbox: '--disable-gpu-sandbox',
    disableGpuShaderDiskCache: '--disable-gpu-shader-disk-cache',
    disableGpuVsync: '--disable-gpu-vsync',
    disableGpuWatchdog: '--disable-gpu-watchdog',
    gpuBlocklistTestGroup: '--gpu-blocklist-test-group',
    gpuDeviceId: '--gpu-device-id',
    gpuDiskCacheSizeKb: '--gpu-disk-cache-size-kb',
    gpuDriverVersion: '--gpu-driver-version',
    gpuLauncher: '--gpu-launcher',
    gpuPreferences: '--gpu-preferences',
    gpuProgramCacheSizeKb: '--gpu-program-cache-size-kb',
    gpuSandboxAllowSysvShm: '--gpu-sandbox-allow-sysv-shm',
    gpuSandboxStartEarly: '--gpu-sandbox-start-early',
    gpuStartupDialog: '--gpu-startup-dialog',
    gpuSubSystemId: '--gpu-sub-system-id',
    gpuVendorId: '--gpu-vendor-id',
    inProcessGpu: '--in-process-gpu',

    disableWebgl: '--disable-webgl',
    disableWebglImageChromium: '--disable-webgl-image-chromium',
    disableWebgl2: '--disable-webgl2',
    webglAntialiasingMode: '--webgl-antialiasing-mode',
    webglMsaaSampleCount: '--webgl-msaa-sample-count',

    disableGlDrawingForTests: '--disable-gl-drawing-for-tests',
    disableGlExtensions: '--disable-gl-extensions',
    disableGlslTranslator: '--disable-glsl-translator',

    webviewDisableAppRecovery: '--webview-disable-app-recovery',
    webviewDisablePackageAllowlistThrottling: '--webview-disable-package-allowlist-throttling',
    webviewDisableSafebrowsingSupport: '--webview-disable-safebrowsing-support',
    webviewEnableAppRecovery: '--webview-enable-app-recovery',
    webviewEnableModernCookieSameSite: '--webview-enable-modern-cookie-same-site',
    webviewMparchFencedFrames: '--webview-mparch-fenced-frames',
    webviewSafebrowsingBlockAllResources: '--webview-safebrowsing-block-all-resources',
    webviewSandboxedRenderer: '--webview-sandboxed-renderer',
    webviewShadowDomFencedFrames: '--webview-shadow-dom-fenced-frames',

    disableWebrtcEncryption: '--disable-webrtc-encryption',
    disableWebrtcHwDecoding: '--disable-webrtc-hw-decoding',
    disableWebrtcHwEncoding: '--disable-webrtc-hw-encoding',
    webrtcEventLogProactivePruningDelta: '--webrtc-event-log-proactive-pruning-delta',
    webrtcEventLogUploadDelayMs: '--webrtc-event-log-upload-delay-ms',
    webrtcEventLogUploadNoSuppression: '--webrtc-event-log-upload-no-suppression',
    webrtcEventLogging: '--webrtc-event-logging',
    webrtcIpHandlingPolicy: '--webrtc-ip-handling-policy',
    webrtcMaxCpuConsumptionPercentage: '--webrtc-max-cpu-consumption-percentage',

    disableCompositedAntialiasing: '--disable-composited-antialiasing',
    disableD3d11: '--disable-d3d11',
    disableDirectComposition: '--disable-direct-composition',
    disableDirectCompositionVideoOverlays: '--disable-direct-composition-video-overlays',
    disableFrameRateLimit: '--disable-frame-rate-limit',
    disableRendererAccessibility: '--disable-renderer-accessibility',
    disableRendererBackgrounding: '--disable-renderer-backgrounding',
    disableMetalShaderCache: '--disable-metal-shader-cache',
    disableNewContentRenderingTimeout: '--disable-new-content-rendering-timeout',
    disableImageAnimationResync: '--disable-image-animation-resync',
    disableNv12DxgiVideo: '--disable-nv12-dxgi-video',
    disablePartialRaster: '--disable-partial-raster',
    disableRtcSmoothnessAlgorithm: '--disable-rtc-smoothness-algorithm',
    disableShaderNameHashing: '--disable-shader-name-hashing',
    disableSkiaRuntimeOpts: '--disable-skia-runtime-opts',
    disableSmoothScrolling: '--disable-smooth-scrolling',
    disableSoftwareCompositingFallback: '--disable-software-compositing-fallback',
    disableSoftwareRasterizer: '--disable-software-rasterizer',
    disableAngleFeatures: '--disable-angle-features',

    enabled2DLayers: '--canvas-2d-layers',
    disableCanvasAa: '--disable-canvas-aa',
    disabled2DCanvasClipAa: '--disable-2d-canvas-clip-aa',
    disabled2DCanvasImageChromium: '--disable-2d-canvas-image-chromium',
    disableReadingFromCanvas: '--disable-reading-from-canvas',
    disabledAccelerated2DCanvas: '--disable-accelerated-2d-canvas',

    noExperiments: '--no-experiments',
    enableLowEndDeviceMode: '--enable-low-end-device-mode',
    crosDisksFake: '--cros-disks-fake',
    denyPermissionPrompts: '--deny-permission-prompts',
    deviceScaleFactor: '--device-scale-factor',
    disableHighresTimer: '--disable-highres-timer',
    disablePushstateThrottle: '--disable-pushstate-throttle',
    disableAutoReload: '--disable-auto-reload',
    disableBackForwardCache: '--disable-back-forward-cache',
    disableBackgroundNetworking: '--disable-background-networking',
    disableBackgroundTimerThrottling: '--disable-background-timer-throttling',
}
