const PAYMENT_STATUS_CREATED = 'Created';
const PAYMENT_STATUS_SUCCESS = 'Success';
const PAYMENT_STATUS_FAILED = 'Failed';

const PAYMENT_METHOD_FREEKASSA = 'Freekassa';

module.exports = {
    PAYMENT_STATUS_CREATED,
    PAYMENT_STATUS_SUCCESS,
    PAYMENT_STATUS_FAILED,
    PAYMENT_METHOD_FREEKASSA,
};
